export const ADD_TO_CARD = "ADD_TO_CARD"
export const DELETE_FROM_CARD = "DELETE_FROM_CARD"
export const UPDATE_URI = "UPDATE_URI"
export const SET_VISITE = "SET_VISITE"
export const SET_ORDER = "SET_ORDER"
export const SET_PAYMENT = "SET_PAYMENT"
